// Predefined skill list — used in Resource Allocation and TM Profile management
// This ensures consistent naming across the entire system.
export const TECH_SKILLS = [
  "React",
  "React Native",
  "Angular",
  "Vue.js",
  "Next.js",
  "Node.js",
  "Express.js",
  "Python",
  "Django",
  "FastAPI",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "PHP",
  "Laravel",
  "Go",
  "Ruby on Rails",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "DevOps",
  "CI/CD",
  "GraphQL",
  "REST API",
  "Microservices",
  "Machine Learning",
  "Data Engineering",
  "Android",
  "iOS",
  "Flutter",
  "Cybersecurity",
  "QA / Testing",
  "UI/UX Design",
  "Cloud Infrastructure",
  "Blockchain",
];
